### PR TITLE
Install mender-artifact.

### PR DESCRIPTION
**Pull request by mattcaron-redlion**

### CODE REVIEW

**Comment by DavidZemon** [comment]
Would it make sense to add this to native instead of linaro? Mender isn't specific to linaro, right?

**Comment by mattcaron-redlion** [comment]
Maybe. I put it in linaro because that's what I'm using and it's what Paul suggested, but I could see putting it in native. @pwalkr , what say you? Native or linaro?

**Comment by pwalkr** [comment]
@DavidZemon @mattcaron-redlion , where mender-artifact goes depends on what it does imho. If it's a distribution utility specific to how we want to distribute images for sitara platforms, then toolchain-linaro seems fit. If artifacts are non-platform specific, and there's a remote chance we could use x86 versions, then `-native`. But I'm also okay putting off a migration to `-native` until we actually need it there.

**Comment by DavidZemon** [comment]
i was thinking not so much x86, but whatever comes after sitara

**Comment by pwalkr** [comment]
Whatever comes after sitara may use something completely different. Or assuming linaro keeps putting out toolchains, we could just bump the version on this repo.

**Review by pwalkr — CHANGES_REQUESTED** [review]
What about putting this after line 46 - after the qemu and linaro installs? Keeps the installs together, and keeps everything before the recursive chown/chmod (in case something new gest installed there)

**Review by DavidZemon — APPROVED** [review]

**Comment by mattcaron-redlion** [comment]
It is not platform specific. There is nothing intrinsically tied to any architecture. It can be used for anything, including existing products (for example, RAM). This is a policy question, not an technology question. But, I don't know that we'd ever need x86, because it's unlikely we'd do an x86 box. But, since all of the specific toolchains are descended from the general toolchain, and this is a general utility, putting it there makes sense, I think.

I have moved it up after line 46.

**Comment by mattcaron-redlion** [comment]
I guess I need to close this and open a new PR for it because github is weird.

**Comment by mattcaron-redlion** [comment]
So, we can use this PR if we ignore the timestamps on the commit. The commit is correct, but the timestamp is wrong.

**Review by DavidZemon — APPROVED** [review]

**Review by pwalkr — APPROVED** [review]

**Pull request merged**
